name: Publish Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  black-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Publish Python Package
        run: poetry publish -r testpypi
