name: Publish Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish-python:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nonebot-plugin-wutheringwaves
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
            fetch-depth: 0
            fetch-tags: true

      - name: Generate Changelog
        id: generate_changelog
        uses: Night-stars-1/changelog-generator-action@main

      - name: Install poetry
        run: pip install poetry

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Run build
        run: poetry build

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2.0.4
        with:
          name: 库街区小助手 ${{ github.ref_name }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
          make_latest: true
